const clinicContacts = {
  FETCH_CLINICS_REQUEST: "FETCH_CLINICS_REQUEST",
  FETCH_CLINICS_SUCCESS: "FETCH_CLINICS_SUCCESS",
  FETCH_CLINICS_FAILURE: "FETCH_CLINICS_FAILURE"
};

export default clinicContacts;
