const waitlistConstants = {
  JOIN_WAITLIST_REQUEST: "JOIN_WAITLIST_REQUEST",
  JOIN_WAITLIST_SUCCESS: "JOIN_WAITLIST_SUCCESS",
  JOIN_WAITLIST_FAILURE: "JOIN_WAITLIST_FAILURE",

  LEAVE_WAITLIST_REQUEST: "LEAVE_WAITLIST_REQUEST",
  LEAVE_WAITLIST_SUCCESS: "LEAVE_WAITLIST_SUCCESS",
  LEAVE_WAITLIST_FAILURE: "LEAVE_WAITLIST_FAILURE",

  GET_WAIT_TIME_REQUEST: "GET_WAIT_TIME_REQUEST",
  GET_WAIT_TIME_SUCCESS: "GET_WAIT_TIME_SUCCESS",
  GET_WAIT_TIME_FAILURE: "GET_WAIT_TIME_FAILURE"
};

export default waitlistConstants;
